
​
 const seedUsers = [
  {
    firstName: "John",
    lastName: "Doe",
    description: "unknown male administrator",
    email: "john.doe@aol.com",
    password: "password123",
    roleId: 1,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    description: "person",
    email: "jane.doe@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Kevin",
    lastName: "De Bruyne",
    description: "person",
    email: "kevin@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Raheem",
    lastName: "Sterling",
    description: "person",
    email: "raheem@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Phil",
    lastName: "Foden",
    description: "person",
    email: "phil@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "John",
    lastName: "Stones",
    description: "person",
    email: "john.stones@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    description: "unknown female administrator",
    email: "john.doe@aol.com",
    password: "password123",
    roleId: 1,
  },
  {
    firstName: "Christian",
    lastName: "Pulisic",
    description: "person",
    email: "christian@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Weston",
    lastName: "McKennie",
    description: "person",
    email: "weston@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Sergino",
    lastName: "Dest",
    description: "person",
    email: "sergino@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Tyler",
    lastName: "Adams",
    description: "person",
    email: "tyler@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Sergio",
    lastName: "Aguero",
    description: "person",
    email: "sergio@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Ferran",
    lastName: "Torres",
    description: "person",
    email: "ferran@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Charles",
    lastName: "Barkley",
    description: "person",
    email: "charles@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Cam",
    lastName: "Newton",
    description: "person",
    email: "cam@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Lionel",
    lastName: "Messi",
    description: "person",
    email: "lionel@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Seth",
    lastName: "Rogen",
    description: "person",
    email: "seth@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Waka",
    lastName: "Flocka Flame",
    description: "person",
    email: "waka@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "David",
    lastName: "Gordon Green",
    description: "person",
    email: "david@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Matt",
    lastName: "Berninger",
    description: "person",
    email: "matt@aol.com",
    password: "password123",
    roleId: 2,
  },
];

module.exports=seedUsers