const seedRoles = [
  {
    name: "admin",
    description: "admin has privilaged access to add products",
  },
  {
    name: "customer",
    description: "Customers can shop and purchase products",
  },
];

const seedUsers = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@aol.com",
    password: "password123",
    roleId: 1,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    email: "jane.doe@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Kevin",
    lastName: "De Bruyne",
    email: "kevin@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Raheem",
    lastName: "Sterling",
    email: "raheem@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Phil",
    lastName: "Foden",
    email: "phil@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "John",
    lastName: "Stones",
    email: "john.stones@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    email: "john1.doe@aol.com",
    password: "password123",
    roleId: 1,
  },
  {
    firstName: "Christian",
    lastName: "Pulisic",
    email: "christian@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Weston",
    lastName: "McKennie",
    email: "weston@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Sergino",
    lastName: "Dest",
    email: "sergino@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Tyler",
    lastName: "Adams",
    email: "tyler@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Sergio",
    lastName: "Aguero",
    email: "sergio@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Ferran",
    lastName: "Torres",
    email: "ferran@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Charles",
    lastName: "Barkley",
    email: "charles@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Cam",
    lastName: "Newton",
    email: "cam@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Lionel",
    lastName: "Messi",
    email: "lionel@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Seth",
    lastName: "Rogen",
    email: "seth@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Waka",
    lastName: "Flocka Flame",
    email: "waka@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "David",
    lastName: "Gordon Green",
    email: "david@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Matt",
    lastName: "Berninger",
    email: "matt@aol.com",
    password: "password123",
    roleId: 2,
  },
  {
    firstName: "Anon",
    lastName: "User",
    email: "email@email.com",
    password: "password123",
    roleId: 2,
  },
];

module.exports = {
  seedUsers,
  seedRoles,
};
